[tool.poetry]
name = "Pyneapple"
version = "1.5.4"
description = "Pyneapple is an advanced tool for analysing multi-exponential signal data in MR DWI images."
authors = [
    "Thomas Thiel <thomas.thiel@hhu.de>",
    "Jonas Jasse, <jonas.jasse@hhu.de>",
]
maintainers = ["Jonas Jasse <jonas.jasse@hhu.de>"]
readme = "README.md"
license = "GPL-3.0-or-later"
homepage = "https://github.com/darksim33/Pyneapple/"
repository = "https://github.com/darksim33/Pyneapple/"
classifiers = [
    "Development Status :: 4 - Beta",
    "Intended Audience :: Science/Research",
    "Natural Language :: English",
    "Operating System :: Microsoft :: Windows :: Windows 10",
    "Operating System :: Microsoft :: Windows :: Windows 11",
    "Operating System :: POSIX :: Linux",
    "Programming Language :: Python :: 3.11",
    "Topic :: Scientific/Engineering :: Image Processing",
    "Topic :: Scientific/Engineering :: Medical Science Apps.",
]
packages = [{ include = "pyneapple", from = "src" }]

[tool.poetry.dependencies]
python = "~3.9 | ~3.10 | ~3.11 | ~3.12"
pathlib = "^1.0.1"
numpy = [
    { version = "^2.1.1", python = "^3.10" },
    { version = "^1.23.0", python = "~3.9" },
]
matplotlib = "^3.7.0"
scipy = "^1.10.1"
opencv-python = "^4.8.0.76"
pandas = "^2.1.3"
openpyxl = "^3.1.2"
tqdm = "^4.66.2"
radimgarray = { path = "src/radimgarray", develop = true }
pygpufit = { path = "src/pygpufit", develop = true }

[tool.poetry.group.dev]
optional = true

[tool.poetry.group.dev.dependencies]
black = "^24.3.0"
pytest = "^8.1.1"
pytest-order = "^1.2.1"
tox = "4.20.0"

[tool.poetry.scripts]

[tool.pytest.ini_options]
markers = ["slow: slow tests", "gpu: gpufit related tests"]

[tool.pyright]
venvPath = ""
venv = ".venv"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
