[General]
Class = "IVIMParams"
description = "Biexponential fitting parameters for kidney data."
fit_type = "multi"
n_pools = 4
max_iter = 250
b_values = [
    0,
    10,
    20,
    30,
    40,
    50,
    70,
    100,
    150,
    200,
    250,
    350,
    450,
    550,
    650,
    750
]

[Model]
model = "biexp"
fit_reduced = false
fit_t1 = false
fit_s0 = true  # Enable S0 fitting

[boundaries.D]
1 = [0.001, 0.0007, 0.05]
2 = [0.02, 0.003, 0.3]

[boundaries.f]
1 = [0.1, 0.01, 0.99]

[boundaries.S]
0 = [210, 10, 10000]  # Add S0 boundaries